[tool.poetry]
name = "maidr"
version = "0.0.1"
description = "Multimodal Access and Interactive Data Representations"
authors = ["JooYoung Seo <jseo1005@illinois.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.7.1"
numpy = "^1.24.3"
seaborn = "^0.12.2"
lxml = "^4.9.2"
htmltools = ">=0.5.1"


[tool.poetry.group.dev.dependencies]
black = "23.3.0"
sphinx = "^7.0.1"
pre-commit = "^3.3.2"
pytest = "^7.3.2"
python-semantic-release = "^8.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.semantic_release]
branch = "main"
version_variable = "maidr/__init__.py:__version__"
upload_to_pypi = "true"
upload_to_release = "true"
