name: "Lint Commit Messages"

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: './commitlint.config.js'
          token: ${{ secrets.GITHUB_TOKEN }}
